version: '3'
services:
  elasticsearch:
    build: ./es
    container_name: "qass-es"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.10
    tty: true

  logstash:
    build: ./logstash
    container_name: "qass-logstash"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/log:/var/log
    depends_on:
      - elasticsearch
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.11
    tty: true

  kibana:
    build: ./kibana
    container_name: "qass-kibana"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.12
    tty: true

networks:
  qass_analytics_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/16

volumes:
  es-data:
    driver: local