version: '3'
services:
  elasticsearch:
    build: ./es
    container_name: "qass-es"
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.10
    tty: true

  kibana:
    build: ./kibana
    container_name: "qass-kibana"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "xpack.graph.enabled=false"
      - "xpack.security.enabled=false"
      - "xpack.ml.enabled=false"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.11
    tty: true

networks:
  qass_analytics_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/16

volumes:
  es-data:
    driver: local