version: '3'
services:
  elasticsearch:
    build: ./es
    container_name: "qass-elasticsearch"
    environment:
      - cluster.name=kibana-cluster
      - node.name=kibana-01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - xpack.monitoring.history.duration=1d
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      # - ./es/config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.10
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  kibana:
    build: ./kibana
    container_name: "qass-kibana"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_MONITORING_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      qass_analytics_net:
        ipv4_address: 172.16.238.11
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  qass_analytics_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/16

volumes:
  es-data:
    driver: local